include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.i69n.dart'

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    always_use_package_imports: true
    directives_ordering: true
    null_check_on_nullable_type_parameter: true
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true